swagger: "2.0"
info:
  description: "Currency application"
  version: "1.0.0"
  title: "Swagger Currency API"
host: "localhost:8080"
basePath: "/currency"
schemes:
  - "http"
paths:
  /healthcheck:
    get:
      summary: "For checking health of API"
      description: "Returns status"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            properties:
              status: 
                type: "string"
              message:
                type: "string"
  /save/{date}:
    get:
      summary: "Saves currency data from external API"
      description: "Returns success status and message"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: date
          required: true
          schema:
            type: string
      responses:
        200:
          description: "successfull operation"
          schema:
            type: "object"
            in: query
            properties:
              success: 
                type: "boolean"
              message:
                type: "string"
  /{date}/{code}:
    get:
      summary: "Get list of currencies"
      description: "Returns a list of currencies with their respective values and dates"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: date
          required: true
          schema:
            type: string
        - in: path
          name: code
          required: true
          schema:
            type: string
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            in: query
            properties:
              success:
                type: "boolean"
                example: true
              message:
                type: "string"
                example: "fetched currencies"
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    title:
                      type: "string"
                      example: "ДОЛЛАР США"
                    code:
                      type: "string"
                      example: "USD"
                    value:
                      type: "number"
                      format: "float"
                      example: 447.29
                    date:
                      type: "string"
                      format: "date-time"
                      example: "2024-03-11T00:00:00Z"
definitions:
  Currency:
    type: "object"
    properties:
      title:
        type: "string"
        example: "ДОЛЛАР США"
      code:
        type: "string"
        example: "USD"
      value:
        type: "number"
        format: "float"
        example: 447.29
      date:
        type: "string"
        format: "date-time"